---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
data("rest_inspec")


rest_inspect = 
  rest_inspec |>
  janitor::clean_names() |>
  mutate(year = format(as.Date(inspection_date, format = "%Y/%m/%d"), "%Y")) |>
  filter(!is.na(score),
         grade == "A", 
         boro == "MANHATTAN", 
         year == 2017) |>
  select(cuisine_description, dba, score, street, zipcode, grade) |>
  mutate(cuisine_description = gsub("Latin .*", "Latin", cuisine_description)) 
  
```

Column {data-width=650}
-----------------------------------------------------------------------

### Different Cuisine Score Boxplot
```{r}
rest_inspect |>
  group_by(cuisine_description) |>
  filter(n()>50) |>
  ungroup() |>
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) |>
  plot_ly(y = ~score, x = ~cuisine_description, type = "box", color = ~cuisine_description, colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Restaurant in Zipcode histogram

```{r}
rest_inspect |>
  count(zipcode) |>
  mutate(zipcode = fct_reorder(as.character(zipcode), n)) |>
  plot_ly(x = ~zipcode, y = ~n, color = ~zipcode, type = "bar", colors = "viridis")
```

### Asian food score changes over time lineplot

thai, japanese, korean, vietnamese, Indonesian food score over time 
```{r}
asian_rest = 
  rest_inspec |>
  janitor::clean_names() |>
   mutate(year = format(as.Date(inspection_date, format = "%Y/%m/%d"), "%Y")) |>
  filter(!is.na(score),
         cuisine_description == c("Thai", "Chinese", "Korean", "Japanese", "Indonesian", "Vietnamese/Cambodian/Malaysia", "Filipino"),
         boro == "MANHATTAN") |>
  select(year, cuisine_description, score) 

asian_rest |>
  group_by (year, cuisine_description) |>
  summarize(ave_score = mean (score)) |>
  ungroup() |>
  plot_ly (x = ~year, y = ~ave_score, color = ~cuisine_description, type = "scatter", mode = "lines+markers", colors = "viridis") 
```

